# SITE CONFIGURATION
baseurl: ""
url: "http://exquisiteinquiri.es"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: ExquisiteInquiri.es
  avatar: 
  favicon: 
  gravatar: # Email MD5 hash
  description: 'An effort to answer the question: "How is design research practiced today?"' # used by search engines

  # Header and footer text
  header_text: >
      <p><strong>What is design research, and how is it practiced today?</strong> To answer this question, I am setting out to collect viewpoints, methodologies, and artifacts from the evolving field of Design Research.</p>
      <p><a href="/about/">About the Project</a> &nbsp;&nbsp;&nbsp; <a href="/contribute/">Contribute</a></p>
  header_text_feature_image: assets/img/hero-bg.jpg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "sylhare"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup
  portfolio: false
  search: false
  tags: false

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Copse|Open+Sans:400,700"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
